### ISSUE TITLE
The device is currently offline.

### ISSUE THREAD

**Issue by hocnguyen** [moderepo/Android-Device-SDK#1]
Hi guys，
I have a problem need to help.
I had build a android device as your sample , I had turn on/off claim mode and get trigger event from android hardware success. But when i send command from app simulator,  I get error "The device is currently offline." although my android device still connect. 
Also I use device simulator is ok.
please help me solve that.
Thanks you so much.

**Comment by honteng** [comment]
Hi!
Thank you for using and developing MODE device. I hope you enjoy our development environment.

"The device is currently offline." means WebSocket from your device is disconnected. I guess disconnection happened when you used device simulator. Because a device can have only one WebSocket connection.

If you want to test now, close both device simulator and Android App and restart Android App only. Then try to send commands again.

But strange thing is that MODECommandListener should reconnect automatically when WebSocket is disconnected. It would be a bug so I will look into it.

Thanks,

**Comment by hocnguyen** [comment]
Hi !
I don't use device simulator, i built on my android hardware, and it still notice to me that message (device offline).
Also, if i use device simulator (from console), when I add it into my home (at app simulator) so status is connected. But when i use android hardware, after i enable claim mode, I added that device then status is disconnected.
please help me review again! 
Thanks

**Comment by honteng** [comment]
I confirmed that the current websocket reconnect logic have a bug. I guess handler and looper problem. I will fix it soon. Can you wait?

**Comment by hocnguyen** [comment]
Thanks for your fervent . I can. Also i will try to fix it while you fixing.

**Comment by honteng** [comment]
Ok, I fixed the problem.

Please git pull and try it again. I confirmed it's working on real device (Samsung Galaxy Tab4) too.

**Comment by hocnguyen** [comment]
yes. it worked. 
Thank you very much.

**Comment by honteng** [comment]
np :-)
